name: CI

on:
  push:
    branches:
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Install Gatsby CLI
      run: npm install -g gatsby-cli
    - name: Install all depedencies (including dev)
      run: npm install
    - name: Build and deploy
      run: npm run deploy -- -r https://${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
